//general
export const SELECT_SUBAPP = "SELECT_APP"
export const SET_NOTICE = "SET_NOTICE"

//users
export const LOGIN_ACTION = "LOGIN"
export const LOGIN_ACTION_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ACTION_FAILED = "LOGIN_FAILED"

export const REGISTER_ACTION = "REGISTER"
export const REGISTER_ACTION_SUCCESS = "REGISTER_SUCESS"
export const REGISTER_ACTION_FAILED = "REGISTER_FAILED"

//tasks
export const ADD_TASK = "ADD_TASK"
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"

export const EDIT_TASK = "EDIT_TASK"
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS"

export const DELETE_TASK = "DELETE_TASK"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"