//general
export const FETCH_API = "FETCH_API"
export const FETCH_API_SUCCESS = "FETCH_API_SUCCESS"
export const SELECT_SUBAPP = "SELECT_APP"
export const SET_NOTICE = "SET_NOTICE"
export const START_SEARCH = "START_SEARCH"
export const EXIT_SEARCH = "EXIT_SEARCH"

//users
export const LOGIN_ACTION = "LOGIN"
export const LOGIN_ACTION_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ACTION_FAILED = "LOGIN_FAILED"

export const REGISTER_ACTION = "REGISTER"
export const REGISTER_ACTION_SUCCESS = "REGISTER_SUCESS"
export const REGISTER_ACTION_FAILED = "REGISTER_FAILED"

//tasks
export const ADD_TASK = "ADD_TASK"
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"

export const EDIT_TASK = "EDIT_TASK"
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS"

export const DELETE_TASK = "DELETE_TASK"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"

export const TOGGLE_COMPLETE_SUCCESS = "TOGGLE_COMPLETE_SUCCESS"

export const SET_TASK = "SET_TASK"
export const HANDLE_SEARCH = "HANDLE_SEARCH"